<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Asambleas.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
    <PackageReference Include="QuestPDF" Version="2025.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Asambleas.Domain\Asambleas.Domain.csproj" />
    <ProjectReference Include="..\Asambleas.Contracts\Asambleas.Contracts.csproj" />
  </ItemGroup>

</Project>
